version: '3.9'

services:
  wazuh-manager:
    image: wazuh/wazuh-manager:latest
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "55000:55000"
    volumes:
      - wazuh_data:/var/ossec/data
    restart: always

volumes
